name: build-project-actions # workflow name
run-name: ${{ github.actor }} is building project Interfaces
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build -x test
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: test -Pheadless
      - name: Package with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: jpackage -x test
